"""
Email Notifier for SLOB Trading System

Sends email notifications for:
- Daily trading summaries
- Critical errors
- Weekly performance reports

Setup (Gmail):
1. Enable 2-Factor Authentication
2. Generate App Password: https://myaccount.google.com/apppasswords
3. Use app password (not regular password)

Environment variables:
- SMTP_SERVER: smtp.gmail.com (default)
- SMTP_PORT: 587 (default)
- SENDER_EMAIL: your-email@gmail.com
- SENDER_PASSWORD: your-app-password
- ALERT_EMAILS: recipient1@example.com,recipient2@example.com
"""

import os
import logging
import smtplib
from email.mime.text import MIMEText
from email.mime.multipart import MIMEMultipart
from datetime import datetime
from typing import Optional, Dict, Any, List

logger = logging.getLogger(__name__)


class EmailNotifier:
    """
    Send trading alerts via email.

    Usage:
        notifier = EmailNotifier()
        notifier.send_daily_summary(stats)
        notifier.send_error_alert("Critical error occurred")
    """

    def __init__(self):
        self.smtp_server = os.getenv('SMTP_SERVER', 'smtp.gmail.com')
        self.smtp_port = int(os.getenv('SMTP_PORT', '587'))
        self.sender = os.getenv('SENDER_EMAIL')
        self.password = os.getenv('SENDER_PASSWORD')

        recipients_str = os.getenv('ALERT_EMAILS', '')
        self.recipients = [email.strip() for email in recipients_str.split(',') if email.strip()]

        self.enabled = bool(self.sender and self.password and self.recipients)

        if not self.enabled:
            logger.warning(
                "Email notifications DISABLED - "
                "Set SMTP credentials and ALERT_EMAILS to enable"
            )
        else:
            logger.info(f"✅ Email notifications enabled ({len(self.recipients)} recipients)")

    def send_email(
        self,
        subject: str,
        body: str,
        html: bool = False,
        recipients: Optional[List[str]] = None
    ):
        """
        Send email notification.

        Args:
            subject: Email subject
            body: Email body (plain text or HTML)
            html: If True, body is HTML
            recipients: Override default recipients
        """
        if not self.enabled:
            return

        try:
            msg = MIMEMultipart('alternative')
            msg['Subject'] = f"[SLOB Bot] {subject}"
            msg['From'] = self.sender
            msg['To'] = ', '.join(recipients or self.recipients)

            if html:
                msg.attach(MIMEText(body, 'html'))
            else:
                msg.attach(MIMEText(body, 'plain'))

            with smtplib.SMTP(self.smtp_server, self.smtp_port) as server:
                server.starttls()
                server.login(self.sender, self.password)
                server.send_message(msg)

            logger.debug(f"Email sent: {subject}")

        except Exception as e:
            logger.error(f"Failed to send email: {e}")

    def send_daily_summary(self, stats: Dict[str, Any]):
        """
        Send daily trading summary.

        Args:
            stats: Daily statistics dictionary
        """
        try:
            date = datetime.now().strftime('%Y-%m-%d')
            subject = f"Daily Summary - {date}"

            # Plain text version
            body_text = f"""
SLOB Trading System - Daily Summary
{'=' * 50}

Date: {date}

Performance
-----------
Setups Detected:    {stats.get('setups_detected', 0)}
Orders Placed:      {stats.get('orders_placed', 0)}
Trades Closed:      {stats.get('trades_closed', 0)}

Win Rate:           {stats.get('win_rate', 0):.1%}
Total P&L:          ${stats.get('total_pnl', 0):.2f}
Best Trade:         ${stats.get('best_trade', 0):.2f}
Worst Trade:        ${stats.get('worst_trade', 0):.2f}

Positions
---------
Active Positions:   {stats.get('active_positions', 0)}
Max Drawdown:       {stats.get('max_drawdown', 0):.1%}

Account
-------
Balance:            ${stats.get('account_balance', 0):.2f}
Equity:             ${stats.get('equity', 0):.2f}

{'=' * 50}
Generated by SLOB Trading Bot
            """

            # HTML version
            body_html = f"""
<html>
<head>
    <style>
        body {{ font-family: Arial, sans-serif; }}
        h1 {{ color: #2c3e50; }}
        table {{ border-collapse: collapse; width: 100%; margin: 20px 0; }}
        th, td {{ padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }}
        th {{ background-color: #3498db; color: white; }}
        .positive {{ color: green; }}
        .negative {{ color: red; }}
        .footer {{ margin-top: 30px; font-size: 12px; color: #7f8c8d; }}
    </style>
</head>
<body>
    <h1>📊 SLOB Trading System - Daily Summary</h1>
    <p><strong>Date:</strong> {date}</p>

    <h2>Performance</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Setups Detected</td><td>{stats.get('setups_detected', 0)}</td></tr>
        <tr><td>Orders Placed</td><td>{stats.get('orders_placed', 0)}</td></tr>
        <tr><td>Trades Closed</td><td>{stats.get('trades_closed', 0)}</td></tr>
        <tr><td>Win Rate</td><td>{stats.get('win_rate', 0):.1%}</td></tr>
    </table>

    <h2>P&L</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr>
            <td>Total P&L</td>
            <td class="{'positive' if stats.get('total_pnl', 0) >= 0 else 'negative'}">
                ${stats.get('total_pnl', 0):.2f}
            </td>
        </tr>
        <tr><td>Best Trade</td><td class="positive">${stats.get('best_trade', 0):.2f}</td></tr>
        <tr><td>Worst Trade</td><td class="negative">${stats.get('worst_trade', 0):.2f}</td></tr>
    </table>

    <h2>Account Status</h2>
    <table>
        <tr><th>Metric</th><th>Value</th></tr>
        <tr><td>Active Positions</td><td>{stats.get('active_positions', 0)}</td></tr>
        <tr><td>Account Balance</td><td>${stats.get('account_balance', 0):.2f}</td></tr>
        <tr><td>Equity</td><td>${stats.get('equity', 0):.2f}</td></tr>
        <tr><td>Max Drawdown</td><td>{stats.get('max_drawdown', 0):.1%}</td></tr>
    </table>

    <div class="footer">
        <p>Generated by SLOB Trading Bot at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
    </div>
</body>
</html>
            """

            self.send_email(subject, body_html, html=True)

        except Exception as e:
            logger.error(f"Error sending daily summary: {e}")

    def send_error_alert(self, error: str, context: Optional[str] = None):
        """
        Send critical error alert.

        Args:
            error: Error message
            context: Optional context (function, module, etc.)
        """
        try:
            subject = "🚨 Critical Error Alert"

            body = f"""
SLOB Trading System - Critical Error
{'=' * 50}

Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{f'Context: {context}' if context else ''}

Error:
{error}

{'=' * 50}
Please investigate immediately.
            """

            self.send_email(subject, body)

        except Exception as e:
            logger.error(f"Error sending error alert: {e}")

    def send_weekly_report(self, stats: Dict[str, Any]):
        """
        Send weekly performance report.

        Args:
            stats: Weekly statistics dictionary
        """
        try:
            week_start = stats.get('week_start', datetime.now().strftime('%Y-%m-%d'))
            week_end = stats.get('week_end', datetime.now().strftime('%Y-%m-%d'))
            subject = f"Weekly Report - {week_start} to {week_end}"

            body = f"""
SLOB Trading System - Weekly Report
{'=' * 50}

Period: {week_start} to {week_end}

Summary
-------
Total Setups:       {stats.get('total_setups', 0)}
Total Trades:       {stats.get('total_trades', 0)}
Wins:               {stats.get('wins', 0)}
Losses:             {stats.get('losses', 0)}
Win Rate:           {stats.get('win_rate', 0):.1%}

Performance
-----------
Total P&L:          ${stats.get('total_pnl', 0):.2f}
Average Win:        ${stats.get('avg_win', 0):.2f}
Average Loss:       ${stats.get('avg_loss', 0):.2f}
Profit Factor:      {stats.get('profit_factor', 0):.2f}
Sharpe Ratio:       {stats.get('sharpe_ratio', 0):.2f}

Risk Metrics
------------
Max Drawdown:       {stats.get('max_drawdown', 0):.1%}
Max Consecutive Losses: {stats.get('max_consecutive_losses', 0)}
Recovery Factor:    {stats.get('recovery_factor', 0):.2f}

Account
-------
Starting Balance:   ${stats.get('starting_balance', 0):.2f}
Ending Balance:     ${stats.get('ending_balance', 0):.2f}
Equity Change:      ${stats.get('equity_change', 0):.2f} ({stats.get('equity_change_pct', 0):.1%})

{'=' * 50}
Generated by SLOB Trading Bot
            """

            self.send_email(subject, body)

        except Exception as e:
            logger.error(f"Error sending weekly report: {e}")

    def send_system_notification(self, event: str, details: Optional[str] = None):
        """
        Send system notification (startup, shutdown, etc.).

        Args:
            event: Event name (e.g., "System Started")
            details: Optional details
        """
        try:
            subject = f"System Notification: {event}"

            body = f"""
SLOB Trading System - Notification
{'=' * 50}

Event: {event}
Time: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

{details if details else 'No additional details.'}

{'=' * 50}
            """

            self.send_email(subject, body)

        except Exception as e:
            logger.error(f"Error sending system notification: {e}")


# Example usage
if __name__ == "__main__":
    # Test email
    notifier = EmailNotifier()

    if notifier.enabled:
        # Test daily summary
        test_stats = {
            'setups_detected': 2,
            'orders_placed': 2,
            'trades_closed': 1,
            'win_rate': 1.0,
            'total_pnl': 850.0,
            'best_trade': 850.0,
            'worst_trade': 0.0,
            'active_positions': 1,
            'max_drawdown': 0.02,
            'account_balance': 51850.0,
            'equity': 51850.0
        }

        notifier.send_daily_summary(test_stats)
        print("✅ Test email sent!")
    else:
        print("❌ Email not configured")
